services:
  web:
    build: .
    working_dir: /data
    command: python routes.py
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: brother
    ports:
      - "3309:3309"
